In [3]:
#array has all varaiables with same data type  but it is similar to list

#import array as arr
#arr.array()
#we  other way
from array import*

In [7]:
vals=array('i',[5,9,-8,7,6])
vals.reverse()
print(vals.buffer_info())  #it gives array address and size
print(vals)

(1615243204240, 5)
6


In [9]:
vals=array('i',[5,9,-8,7,6])
for i in range(len(vals)):   #if we want to have line by line
    print(vals[i])

5
9
-8
7
6


In [10]:
vals=array('u',['l','o','v','e'])  #unicode as u it gives characters
for i in range(len(vals)):   #if we want to have line by line
    print(vals[i])

l
o
v
e


In [12]:
vals=array('i',[5,9,8,7,6])
newarr=array(vals.typecode,(a*a for a in  vals))
for e in newarr:
    print(e)

25
81
64
49
36


In [5]:
from array import *
arr=array('i',[])
n=int(input("enter the lenght of the array"))
for i in range(n):
    x=int(input("enter the next value"))
    arr.append(x)
print(arr)

val=int(input("enter the value for search"))  #we are finding index no
k=0
for j in arr:
    if j==val:
        print(k)
        break
    k+=1
    
    #another method to find the index no using funtions
print(arr.index(val))
        

enter the lenght of the array3
enter the next value5
enter the next value6
enter the next value7
array('i', [5, 6, 7])
enter the value for search7
2
2


In [6]:
#for two dimensional arrays or multi dimensional arrays above methods are not useful so we use here numpy 
#in numpy mentioning type is optional
#they are six ways to create arrays i.e array(),linspace(),logspace(),arange(),zeros(),ones()
import numpy

In [9]:
#ways of creating arrays in numpy

from numpy import *
arr=array([1,7,8,9,76.9])
print(arr.dtype)

float64


In [12]:
from numpy import *
arr=linspace(0,15,16)   #it has start,stop,steps
print(arr)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [16]:
arr=arange(1,15,3) #it has start,stop,steps here step is see the output
print(arr)

[ 1  4  7 10 13]


In [17]:
arr=logspace(1,15,3) #it has start,stop,steps here step is see the output
print(arr)

[1.e+01 1.e+08 1.e+15]


In [18]:
arr=zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [20]:
arr=ones(5)
print(arr)
arr=ones(5,int)
print(arr)

[1. 1. 1. 1. 1.]
[1 1 1 1 1]


In [22]:

from numpy import *
arr1=array([1,7,8,9,76.9])
arr=arr+3
print(arr)

[ 4.  10.  11.  12.  79.9]


In [23]:
arr1=array([1,7,8,9,76.9])
arr2=array([1,7,8,98,7.9])
arr3=arr1+arr2
print(arr3)

[  2.   14.   16.  107.   84.8]


In [27]:
arr1=array([1,7,8,9,76.9])
print(sin(arr1))   #we can use all the trignometric functions and log,sqrt,sum,min,max,sort,unique
print(sqrt(arr1))
print(sum(arr1))

[0.84147098 0.6569866  0.98935825 0.41211849 0.99761906]
[1.         2.64575131 2.82842712 3.         8.76926451]
101.9


In [28]:
arr1=array([1,7,8,9,76.9])
arr2=array([1,7,8,98,7.9])
print(concatenate([arr1,arr2]))

[ 1.   7.   8.   9.  76.9  1.   7.   8.  98.   7.9]


In [32]:
#copying an array-it has 2-shallow copy and deep copy 

arr1=array([1,7,8,9,76.9])
arr2=arr1.view()
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

#shallow copy-it copt the elements but both the arrays will dependend on each other


arr1=array([1,7,8,9,76.9])
arr2=arr1.view()
arr1[2]=65  #here two arrays are changing see the output
print(arr1)
print(arr2)

#deep copy-it copt the elements but both the arrays will not dependend on each other

arr1=array([1,7,8,9,76.9])
arr2=arr1.copy()
arr1[2]=65  #here onlu array1 is changing see the output
print(arr1)
print(arr2)

[ 1.   7.   8.   9.  76.9]
[ 1.   7.   8.   9.  76.9]
2755247402128
2755269486992
[ 1.   7.  65.   9.  76.9]
[ 1.   7.  65.   9.  76.9]
[ 1.   7.  65.   9.  76.9]
[ 1.   7.   8.   9.  76.9]


In [43]:
#working with matrix 

arr1=array([
                [8,9,8,5,6,65] ,
                [9,6,5,65,43,76]
    
           ])

arr2=arr1.flatten()   #it converts multi` dimensional array to one dimensional array
arr3=arr2.reshape(4,3)   #this function converts one dimensional array to multi dimensional array
arr3=arr2.reshape(2,2,3) 
print(arr1.dtype)
print(arr1.ndim)  #it gives the dimensional of the array
print(arr1.size)
print(arr2)
print(arr3)

int32
2
12
[ 8  9  8  5  6 65  9  6  5 65 43 76]
[[[ 8  9  8]
  [ 5  6 65]]

 [[ 9  6  5]
  [65 43 76]]]


In [47]:
arr1=array([
                [8,9,8,8] ,
                [9,43,7,6]
    
           ])
m=matrix(arr1)  #we r converting here two dimensional array into matrix
#above three steps can be written as
n = matrix('1 2 3 4 ; 5 6 7 8')
print(m)
print(n)

[[ 8  9  8  8]
 [ 9 43  7  6]]
[[1 2 3 4]
 [5 6 7 8]]


In [50]:
#diagnol elements

n = matrix('1 2 3 4 ; 5 6 7 8')
print(diagonal(n))
print(n.min())
print(n.max())

[1 6]
1
8


In [51]:
#adding matrices

n1 = matrix('1 2 3 4 ; 5 6 7 8')
n2 = matrix('3 9 4 5 ; 9 8 7 8')
n3=n1 + n2
print (n3)

[[ 4 11  7  9]
 [14 14 14 16]]
